---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-px-image-repository
  namespace: portworx
spec:
  type: kv-v2 
  mount: {{ .Values.mgmt.vault.vault_engine }}
  path: preprod/{{ splitList "-" .Values.mgmt.cluster.name | first }}/portworx/px-image-repository
  destination:
    name: px-image-repository
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default