---
apiVersion: cluster.open-cluster-management.io/v1beta1 
kind: Placement
metadata:
  name: mano-placement
  namespace: policies-mano
spec:
  clusterSets:
    - mano-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            gitops_acm_config: Active
...
