---
apiVersion: cluster.open-cluster-management.io/v1beta1 
kind: Placement
metadata:
  name: mano-placement-active
  namespace: policies-mano
spec:
  clusterSets:
    - mano-clusters
  predicates:
    - requiredClusterSelector:
        claimSelector:
          matchExpressions:
            - key: custom.hub-status
              operator: In
              values:
               - active
        labelSelector:
          matchLabels:
            gitops_acm_config: Active
...