---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-site-secret
  namespace: ztp-policy
spec:
  type: kv-v2 
  mount: {{ .Values.mgmt.vault.vault_engine }}
  path: preprod/{{ splitList "-" .Values.mgmt.cluster.name | first }}/gitops/site-secret
  destination:
    name: site-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default