---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-ldap-auth-secret
  namespace: openshift-config
spec:
  type: kv-v2 
  mount: {{ .Values.mgmt.vault.vault_engine }}
  path: preprod/{{ splitList "-" .Values.mgmt.cluster.name | first }}/authentication/ldap-auth-secret
  destination:
    name: ldap-auth-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-ldap-group-sync-creds
  namespace: openshift-authentication
spec:
  type: kv-v2 
  mount: {{ .Values.mgmt.vault.vault_engine }}
  path: preprod/{{ splitList "-" .Values.mgmt.cluster.name | first }}/authentication/ldap-auth-secret
  destination:
    name: ldap-group-sync-creds
    create: true
    transformation:
      excludes:
        - .*
      templates:
        bind_password:
          text: '{{ "{{ .Secrets.bindPassword }}" }}'
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default
