---
apiVersion: v1
kind: Node
metadata:
  labels:
    machineconfiguration.openshift.io/role: appworker100g
    node-role.kubernetes.io/appworker100g: ""
    feature.node.kubernetes.io/network-sriov.capable: "true"
    node-role.kubernetes.io/AppworkercMG: ""
  name: DOMAIN_EXAMPLE_40.COM
  annotations:
    ran.openshift.io/ztp-deploy-wave: "1"
spec: {}
...
