---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace
  name: kubernetes-nmstate-operator
  channel: stable
  installPlanApproval: '{{hub fromConfigMap "ztp-policy" "site-data" (printf "install-plan-approval") hub}}'
  startingCSV: kubernetes-nmstate-operator.4.18.0-202509101149
#status:
#  state: AtLatestKnown
...
