---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/description: OADP Operator Installation
  name: operator-install-oadp
  namespace: policies
spec:
  disabled: false
  policy-templates:
#Create namespace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: oadp-namespace
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: open-cluster-management-backup
              labels:
                openshift.io/cluster-monitoring: "true"
#Create the operator group, when the namespace is ready
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: oadp-namespace
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: oadp-operator-group
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: redhat-oadp-operator-group # Defined by ACM to manage the object
              namespace: open-cluster-management-backup
            labels:
              installer.name: multiclusterhub
              installer.namespace: open-cluster-management
            spec:
              targetNamespaces:
                - open-cluster-management-backup
#Create the subscription when the operator group is ready
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: oadp-operator-group
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: oadp-subscription
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: redhat-oadp-operator # Defined by ACM to manage the object
              namespace: open-cluster-management-backup
              labels:
                operators.coreos.com/redhat-oadp-operator.open-cluster-management-backup: ""
            spec:
              channel: '{{hub fromConfigMap "policies-mano" "operators-version" "oadp-channel" hub}}'
              installPlanApproval: Manual
              name: redhat-oadp-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
              startingCSV: '{{hub fromConfigMap "policies-mano" "operators-version" "oadp-startingCSV" hub}}'
#Approve the Install plan when it has been detected
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: oadp-subscription
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name:oadp-installplan-approve
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates-raw: |
          {{- range $installplan := (lookup "operators.coreos.com/v1alpha1" "InstallPlan" "open-cluster-management-backup" "").items }}
            {{- range $installplan.spec.clusterServiceVersionNames }}
            {{- if eq . "{{hub fromConfigMap "policies-mano" "operators-version" "oadp-startingCSV" hub}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: InstallPlan
                metadata:
                  namespace: open-cluster-management-backup
                  name: '{{ $installplan.metadata.name }}'
                spec:
                  approved: true
            {{- end }}
            {{- end }}
          {{- end }}
#Check the CSV
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: oadp-installplan-approve
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: oadp-csv-check
      spec:
        pruneObjectBehavior: None
        remediationAction: inform
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: ClusterServiceVersion
            metadata:
              name: '{{hub fromConfigMap "policies-mano" "operators-version" "oadp-startingCSV" hub}}'
              namespace: open-cluster-management-backup
            status:
              phase: Succeeded
...