---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ch-5gc-amf-01-a-prod-backbone
spec:
  desiredState:
    interfaces:
      - description: ch-5gc-amf-01-a-prod-backbone vlan sub-interface
        mtu: 9000
        name: bond2.3036
        state: up
        type: vlan
        vlan:
          base-iface: bond2
          id: 3036
          reorder-headers: true
  nodeSelector:
    node-role.kubernetes.io/appworker100g: ""
...