---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ch-5gc-scp-01-a-prod-tcp
spec:
  desiredState:
    interfaces:
      - description: ch-5gc-scp-01-a-prod-tcp vlan sub-interface
        mtu: 9000
        name: bond2.3054
        state: up
        type: vlan
        vlan:
          base-iface: bond2
          id: 3054
  nodeSelector:
    node-role.kubernetes.io/appworker25g: ""
...