---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: remove-bond1-ch-5gc-n3i-01-a-prod-oam
spec:
  desiredState:
    interfaces:
      - description: ch-5gc-n3i-01-a-prod-oam vlan sub-interface
        mtu: 9000
        name: bond1.3028
        state: absent
        type: vlan
        vlan:
          base-iface: bond1
          id: 3028
  nodeSelector:
    node-role.kubernetes.io/appworker100g: ""
...