---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: remove-old-gateway-1-egress-vlan
spec:
  nodeSelector: 
    kubernetes.io/hostname: "DOMAIN_EXAMPLE_19.COM"
  desiredState:
    interfaces:
      - name: bond1.3076
        type: vlan
        state: absent
        mtu: 9000
        vlan:
          base-iface: bond1
          id: 3076
      - name: bond1.3077
        type: vlan
        state: absent
        mtu: 9000
        vlan:
          base-iface: bond1
          id: 3077
      - name: bond1.3078
        type: vlan
        state: absent
        mtu: 9000
        vlan:
          base-iface: bond1
          id: 3078          
...