---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: remove-vlan-3012-ch-5gc-ncd-01-a-prod-oam
spec:
  desiredState:
    interfaces:
      - description: ch-5gc-ncd-01-a-prod-oam vlan sub-interface
        mtu: 9000
        name: bond2.3012
        state: absent
        type: vlan
        vlan:
          base-iface: bond2
          id: 3012
  nodeSelector:
    node-role.kubernetes.io/appworker25g: ""
...