---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: storage-network-vlan-a2-worker-009
spec:
  desiredState:
    interfaces:
      - description: storage vlan sub-interface
        mtu: 9000
        name: bond0.1221
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 1221
        ipv4:
          address:
          - ip: IP_ADDRESS_112
            prefix-length: 24
          enabled: true
    routes:
      config:
      - destination: IP_ADDRESS_30/24
        next-hop-address: IP_ADDRESS_31
        next-hop-interface: bond0.1221
        table-id: 254
  nodeSelector:
    kubernetes.io/hostname: "DOMAIN_EXAMPLE_26.COM"
...
