apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/description: Replace SSL CA certificate in the workload clusters kubeconfig files to match the updated API service CA
  name: update-kubeconfig-ca
  namespace: policies-mano
spec:
  disabled: false
  dependencies:
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: cert-api-replace
    namespace: policies-mano
  policy-templates:
  # Create a service account and clusterrolebinding to run the script
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: update-kubeconfig-ca-create-service-account
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates-raw: |
          {{- range (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
          {{- if not (eq .metadata.name "local-cluster") }}
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: update-kubeconfig
                namespace: '{{ .metadata.name }}'
          - complianceType: musthave
            objectDefinition:
              apiVersion: rbac.authorization.k8s.io/v1
              kind: RoleBinding
              metadata:
                name: update-kubeconfig-{{ .metadata.name }}
                namespace: '{{ .metadata.name }}'
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: edit
              subjects:
              - kind: ServiceAccount
                name: update-kubeconfig
                namespace: '{{ .metadata.name }}'
          {{- end }}
          {{- end }}
  #Create Job to update kubeconfig in secret
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: update-kubeconfig-ca-create-service-account
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: update-kubeconfig-ca-create-job
      spec:
        pruneObjectBehavior: DeleteAll
        remediationAction: enforce
        severity: high
        object-templates-raw: |
          {{- range (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
          {{- if not (eq .metadata.name "local-cluster") }}
          - complianceType: musthave
            objectDefinition:
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: update-kubeconfig-ca
                namespace: '{{ .metadata.name }}'
              spec:
                backoffLimit: 2
                completions: 1
                parallelism: 1
                template:
                  metadata:
                    name: update-kubeconfig-ca
                  spec:
                    containers:
                    - name: update
                      image: registry.redhat.io/openshift4/ose-cli
                      command: 
                        - /bin/bash
                        - -c
                        - |
                          sed  "s/certificate-authority-data:.*$/certificate-authority-data: {{ fromConfigMap "policies-mano" "custom-ca-bundle" "CA.cer" | base64enc }}/" data/kubeconfig > /tmp/kubeconfig
                          sed  "s/certificate-authority-data:.*$/certificate-authority-data: {{ fromConfigMap "policies-mano" "custom-ca-bundle" "CA.cer" | base64enc }}/" data/raw-kubeconfig > /tmp/raw-kubeconfig 
                          # If the secret exists, delete it otherwise the creation fails because the existing secret cannot be overwritten.
                          if $(oc get secret {{ .metadata.name }}-admin-kubeconfig-tmp &>/dev/null)
                          then 
                            oc delete secret {{ .metadata.name }}-admin-kubeconfig-tmp
                          fi
                          oc create secret generic {{ .metadata.name }}-admin-kubeconfig-tmp --from-file=/tmp/kubeconfig --from-file=/tmp/raw-kubeconfig
                      volumeMounts:
                        - name: kubeconfig
                          mountPath: "/data"
                    volumes:
                      - name: kubeconfig
                        secret:
                          secretName: '{{ .metadata.name }}-admin-kubeconfig'
                          defaultMode: 0755
                    restartPolicy: Never
                    terminationGracePeriodSeconds: 30
                    activeDeadlineSeconds: 300
                    dnsPolicy: "ClusterFirst"
                    serviceAccountName: update-kubeconfig
                    serviceAccount: update-kubeconfig
          {{- end }}
          {{- end }}
  #Delete failing old job
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: update-kubeconfig-ca-create-job
       namespace: ""
       compliance: NonCompliant
    ignorePending: true
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: update-kubeconfig-ca-delete-job
      spec:
        remediationAction: enforce
        severity: high
        evaluationInterval:
          noncompliant: 30s
        object-templates-raw: |
          {{- range (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
          {{- if not (eq .metadata.name "local-cluster") }}
          - complianceType: mustnothave
            objectDefinition:
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: update-kubeconfig-ca
                namespace: '{{ .metadata.name }}'
          {{- end }}
          {{- end }}
  #Check Job status
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: update-kubeconfig-ca-create-job
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: update-kubeconfig-ca-check-job
      spec:
        remediationAction: inform
        severity: high
        object-templates-raw: |
          {{- range (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
          {{- if not (eq .metadata.name "local-cluster") }}
          - complianceType: musthave
            objectDefinition:
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: update-kubeconfig-ca
                namespace: '{{ .metadata.name }}'
              status:
                conditions:
                  - type: Complete
                    status: 'True'
                succeeded: 1
          {{- end }}
          {{- end }}
  #Update actual admin kubeconfig secret
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: update-kubeconfig-ca-check-job
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: update-kubeconfig-ca-actual
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates-raw: |
          {{- range (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
          {{- if not (eq .metadata.name "local-cluster") }}
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: '{{ .metadata.name }}-admin-kubeconfig'
                namespace: '{{ .metadata.name }}'
              data:
                kubeconfig: '{{ fromSecret .metadata.name (printf "%s-admin-kubeconfig" .metadata.name) "kubeconfig" }}'
                raw-kubeconfig: '{{ fromSecret .metadata.name (printf "%s-admin-kubeconfig" .metadata.name) "raw-kubeconfig" }}'
              type: Opaque
          {{- end }}
          {{- end }}
