---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    pools.operator.machineconfiguration.openshift.io/appworker25g: ""
    nokia-role/appworkerconfig: ""
  name: appworker25g
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
        - appworker25g
        - worker
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/appworker25g: ""
...