---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    pools.operator.machineconfiguration.openshift.io/gateway: ""
  name: gateway
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
        - gateway
        - worker
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/gateway: ""
...