apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: 5gc-ncm-01-oam-dual-ipaddresspool
  namespace: metallb-system
  annotations:
    metallb.universe.tf/address-pool: 5gc-ncm-01-oam-dual-ipaddresspool
spec:
  addresses:
    - IP_ADDRESS_44/27
    - 2001:41d8:1:b007::/64
  autoAssign: false