apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: 5gc-nrf-01-sig-dual-ipaddresspool
  namespace: metallb-system
  annotations:
    metallb.universe.tf/address-pool: 5gc-nrf-01-sig-dual-ipaddresspool
spec:
  addresses:
    - IP_ADDRESS_64/27
    - 2001:41d8:1:b02b::/64
  autoAssign: false