apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: 5gc-nef-01-internet-dual-ipaddresspool
  namespace: metallb-system
  annotations:
    metallb.universe.tf/address-pool: 5gc-nef-01-internet-dual-ipaddresspool
spec:
  addresses:
    - IP_ADDRESS_129/27
    - 2001:41d8:1:b03d::/64
  autoAssign: false