---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: jz-5gc-aaa-01-a-prod-envoy
spec:
  desiredState:
    interfaces:
      - description: jz-5gc-aaa-01-a-prod-envoy vlan sub-interface
        mtu: 9000
        name: bond2.3008
        state: up
        type: vlan
        vlan:
          base-iface: bond2
          id: 3008
  nodeSelector:
    node-role.kubernetes.io/appworker25g: ""
...