---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: jz-5gc-udm-01-a-prod-hsm-lan-2
spec:
  desiredState:
    interfaces:
      - description: jz-5gc-udm-01-a-prod-hsm-lan-2 vlan sub-interface
        mtu: 9000
        name: bond2.2730
        state: up
        type: vlan
        vlan:
          base-iface: bond2
          id: 2730
  nodeSelector:
    node-role.kubernetes.io/appworker25g: ""
...