---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-aap-password
  namespace: ansible-automation-platform
spec:
  type: kv-v2 
  mount: {{ .Values.mgmt.vault.vault_engine }}
  path: preprod/{{ splitList "-" .Values.mgmt.cluster.name | first }}/ansible/aap-password
  destination:
    name: aap-custom-password
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default