---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-workers-ps1-configuration
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,IyBjdXN0b20gUFMxIHdpdGggRlFETiBpbnN0ZWFkIG9mIHNob3J0IG5hbWUKZXhwb3J0IFBTMT0iW1x1QFxIIFxXXVwkICIK
        mode: 0644
        overwrite: true
        path: /etc/profile.d/ps1.sh
...
