---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-redhat-operator-index-v4-18
  namespace: openshift-marketplace
spec:
  image: DOMAIN_EXAMPLE_15.COM/openshift/redhat/redhat-operator-index:v4.18
  sourceType: grpc
...
