---
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: itms-generic-0
spec:
  imageTagMirrors:
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/ubi8
    - DOMAIN_EXAMPLE_15.COM/openshift/ubi8  
    source: registry.redhat.io/ubi8
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/ubi9
    - DOMAIN_EXAMPLE_15.COM/openshift/ubi9
    source: registry.redhat.io/ubi9
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/rhel9
    - DOMAIN_EXAMPLE_15.COM/openshift/rhel9
    source: registry.redhat.io/rhel9
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/openshift4
    - DOMAIN_EXAMPLE_15.COM/openshift/openshift4
    source: registry.redhat.io/openshift4
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/telefonica
    - DOMAIN_EXAMPLE_15.COM/openshift/telefonica
    source: docker.io/telefonica
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/rhacm2
    - DOMAIN_EXAMPLE_15.COM/openshift/rhacm2
    source: registry.redhat.io/rhacm2
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift
    - DOMAIN_EXAMPLE_15.COM/openshift
    source: registry.redhat.io
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/ansible-automation-platform-24
    - DOMAIN_EXAMPLE_15.COM/openshift/ansible-automation-platform-24
    source: registry.redhat.io/ansible-automation-platform-24
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/openshift/release-images
    - DOMAIN_EXAMPLE_31.COM/openshift/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/redhat/certified-operator-index
    source: DOMAIN_EXAMPLE_15.COM/openshift/redhat/certified-operator-index
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/redhat/community-operator-index
    source: DOMAIN_EXAMPLE_15.COM/openshift/redhat/community-operator-index
  - mirrors:
    - DOMAIN_EXAMPLE_31.COM/openshift/redhat/redhat-operator-index
    source: DOMAIN_EXAMPLE_15.COM/openshift/redhat/redhat-operator-index
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/cluster-observability-operator
    - DOMAIN_EXAMPLE_31.COM/openshift/cluster-observability-operator
    source: registry.redhat.io/cluster-observability-operator
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/advanced-cluster-security
    - DOMAIN_EXAMPLE_31.COM/openshift/advanced-cluster-security
    source: registry.redhat.io/advanced-cluster-security
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/amq-streams
    - DOMAIN_EXAMPLE_31.COM/openshift/amq-streams
    source: registry.redhat.io/amq-streams
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/openshift-logging
    - DOMAIN_EXAMPLE_31.COM/openshift/openshift-logging
    source: registry.redhat.io/openshift-logging
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/container-native-virtualization
    - DOMAIN_EXAMPLE_31.COM/openshift/container-native-virtualization
    source: registry.redhat.io/container-native-virtualization
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx
    - DOMAIN_EXAMPLE_31.COM/portworx
    source: openstorage
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx/sig-storage
    - DOMAIN_EXAMPLE_31.COM/portworx/sig-storage
    source: registry.k8s.io/sig-storage
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx/prometheus-operator
    - DOMAIN_EXAMPLE_31.COM/portworx/prometheus-operator
    source: quay.io/prometheus-operator
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx/prometheus
    - DOMAIN_EXAMPLE_31.COM/portworx/prometheus
    source: quay.io/prometheus
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx
    - DOMAIN_EXAMPLE_31.COM/portworx
    source: registry.k8s.io
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx
    - DOMAIN_EXAMPLE_31.COM/portworx
    source: registry.k8s.io
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx
    - DOMAIN_EXAMPLE_31.COM/portworx
    source: nginxinc
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx
    - DOMAIN_EXAMPLE_31.COM/portworx
    source: portworx
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx
    - DOMAIN_EXAMPLE_31.COM/portworx
    source: purestorage
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/portworx/jetstack
    - DOMAIN_EXAMPLE_31.COM/portworx/jetstack
    source: quay.io/jetstack
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift
    - DOMAIN_EXAMPLE_31.COM/openshift
    source: purestorage
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/jetstack
    - DOMAIN_EXAMPLE_31.COM/openshift/jetstack
    source: quay.io/jetstack
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift
    - DOMAIN_EXAMPLE_31.COM/openshift
    source: nginxinc
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift
    - DOMAIN_EXAMPLE_31.COM/openshift
    source: registry.k8s.io
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/prometheus
    - DOMAIN_EXAMPLE_31.COM/openshift/prometheus
    source: quay.io/prometheus
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/prometheus-operator
    - DOMAIN_EXAMPLE_31.COM/openshift/prometheus-operator
    source: quay.io/prometheus-operator
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift
    - DOMAIN_EXAMPLE_31.COM/openshift
    source: portworx
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/sig-storage
    - DOMAIN_EXAMPLE_31.COM/openshift/sig-storage
    source: registry.k8s.io/sig-storage
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift
    - DOMAIN_EXAMPLE_31.COM/openshift
    source: openstorage
  - mirrors:
    - DOMAIN_EXAMPLE_15.COM/openshift/opstree
    - DOMAIN_EXAMPLE_31.COM/openshift/opstree
    source: quay.io/opstree
  - mirrors:
      - DOMAIN_EXAMPLE_31.COM/portworx
      - DOMAIN_EXAMPLE_15.COM/portworx
    source: DOMAIN_EXAMPLE_21.COM/portworx
  - mirrors:
      - DOMAIN_EXAMPLE_31.COM/portworx
      - DOMAIN_EXAMPLE_15.COM/portworx
    source: docker.io/portworx
  - mirrors:
      - DOMAIN_EXAMPLE_31.COM/openshift/community-operator-pipeline-prod
      - DOMAIN_EXAMPLE_15.COM/openshift/community-operator-pipeline-prod
    source: quay.io/community-operator-pipeline-prod
...
