---
- name: "Vault action - renew secret_id and update consumer secrets"
  hosts: "localhost"
  gather_facts: false
  connection: "local"
  tasks:

    - name: Get auth token from approle
      ansible.builtin.shell: >
        curl -k -s --request POST
        --header "X-Vault-Namespace: {{ vault.vault_namespace }}"
        --data '{"role_id": "{{ vault_roleID }}", "secret_id": "{{ vault_secretID }}"}'
        {{ vault.vault_url }}/v1/auth/approle/login
      register: approle_token_raw

    - name: Extract auth client token
      ansible.builtin.set_fact:
        approle_token: "{{ (approle_token_raw.stdout | from_json).auth.client_token }}"  

    - name: Renew secret_id
      ansible.builtin.shell: >
        curl -k -X POST -H "X-Vault-Token: {{ approle_token }}" -H "X-Vault-Namespace: {{ vault.vault_namespace }}" 
        https://DOMAIN_EXAMPLE_30.COM:8200/v1/auth/approle/role/rhocp-approle/secret-id
      register: secret_id_raw

    - name: Extract secret_id
      ansible.builtin.set_fact:
        secret_id_renew: "{{ (secret_id_raw.stdout | from_json).data.secret_id }}"

    - name: Update consumer Secret for each namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: approle-creds
            namespace: "{{ item }}"
          type: Opaque
          stringData:
            id: "{{ secret_id_renew }}" 
      loop: 
        - ansible-automation-platform
        - openshift-authentication
        - openshift-config
        - ztp
        - ztp-policy
        - openshift-monitoring
        - open-cluster-management-backup
        - portworx
        - quay-enterprise
        - test1-preprod1
        - test2-preprod1
