---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: vault-secret-id-renewal
  namespace: imperative
spec:
  schedule: "0 10 * * 1"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: imperative-sa

          volumes:
          - name: workspace
            emptyDir: {}
          - name: vault-secret-vol
            secret:
              secretName: ansible-vault-password

          initContainers:
          - name: git-clone
            image: {{ .Values.mgmt.vault.image }}
            env:
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-creds
                  key: username
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: git-creds
                  key: password
            - name: GIT_URL
              valueFrom:
                secretKeyRef:
                  name: git-creds
                  key: url
            - name: GIT_BRANCH
              valueFrom:
                secretKeyRef:
                  name: git-creds
                  key: branch
            - name: GIT_SSL_NO_VERIFY
              value: "true"
            command: 
            - /bin/sh
            - -c
            - "git clone -b ${GIT_BRANCH} https://${GIT_USERNAME}:${GIT_TOKEN}@${GIT_URL} /workspace/repo"
            volumeMounts:
            - name: workspace
              mountPath: /workspace

          containers:
          - name: ansible-runner
            image: {{ .Values.mgmt.vault.image }}
            workingDir: /workspace/repo
            command: 
            - ansible-playbook
            - -i
            - inventory/inventory-{{ .Values.mgmt.cluster.name }}.{{ .Values.mgmt.cluster.domain }}.yaml
            - -e
            - "@inventory/vault-{{ .Values.mgmt.cluster.name }}.yaml"
            - --vault-password-file
            - /etc/ansible-vault/password
            - /workspace/repo/ansible/playbook_secret_id_renewal.yaml

            volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: vault-secret-vol
              mountPath: /etc/ansible-vault
              readOnly: true

          restartPolicy: Never