---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iscsi-updater
  namespace: portworx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iscsi-updater-privileged
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: iscsi-updater
    namespace: portworx
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iscsi-initiator-updater
  namespace: portworx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    matchLabels:
      app: iscsi-initiator-updater
  template:
    metadata:
      labels:
        app: iscsi-initiator-updater
    spec:
      serviceAccountName: iscsi-updater
      hostPID: true
      hostNetwork: true
      tolerations:
        - operator: Exists
      nodeSelector: {}
      containers:
      - name: updater
        image: {{ .Values.mgmt.portworx.iscsiImage }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - /bin/bash
          - -c
          - |
            set -euxo pipefail

            HOST=${NODE_NAME}
            echo "[INFO] Running on $HOST"
            shortname="${HOSTNAME%%.*}"
            shortname_upper="${shortname^^}"
            NEW_IQN="{{ .Values.mgmt.portworx.base_iscsiIQN }}:$shortname_upper"
            TARGET_FILE="/rootfs/etc/iscsi/initiatorname.iscsi"
            echo "[INFO] Writing IQN=$NEW_IQN into $TARGET_FILE"
            echo "InitiatorName=$NEW_IQN" > "${TARGET_FILE}"
            cat "${TARGET_FILE}"
            echo "[INFO] Restarting iscsid service"
            chroot /rootfs /bin/systemctl restart iscsid
            echo "[INFO] Done."
            sleep infinity
        volumeMounts:
          - name: rootfs
            mountPath: /rootfs
      volumes:
        - name: rootfs
          hostPath:
            path: /