---
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: 5gc-ncd-01-oam-ipv6-egressip
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: 5gc-ncd-01-a-ns
  egressIPs:
  - 2001:41d8:1:b100:0:24:0:90
  - 2001:41d8:1:b100:0:24:0:91
...