apiVersion: v1
kind: Secret
metadata:
  name: vmo2-intermediate-ca-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.mgmt.intermediateCA.tls.crt }}
  tls.key: {{ .Values.mgmt.intermediateCA.tls.key }}
