---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registries-ca-bundle
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  {{ .Values.mgmt.quay.fqdn }}: |
{{ .Values.mgmt.authentication.ldap.crt  | b64dec | indent 4 }}
  updateservice-registry: |
{{ .Values.mgmt.ztp.http_server_certificate_b64 | b64dec | indent 4 }}