---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-quay-config-bundle-ldap
  namespace: quay-enterprise
spec:
  type: kv-v2 
  mount: {{ .Values.mgmt.vault.vault_engine }}
  path: preprod/{{ splitList "-" .Values.mgmt.cluster.name | first }}/quay/quay-config-bundle-ldap
  destination:
    name: quay-config-bundle-ldap
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-secrets-operator/default