---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/description: Create RHACS Secured cluster
  name: rhacs-secured-cluster
  namespace: policies
spec:
  disabled: false
  dependencies:
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: rhacs-central
    namespace: policies-mano
  policy-templates:
  # secured namespace (in MANO same as central)
#    - objectDefinition:
#        apiVersion: policy.open-cluster-management.io/v1
#        kind: ConfigurationPolicy
#        metadata:
#          name: stackrox-namespace
#        spec:
#          pruneObjectBehavior: None
#          remediationAction: enforce
#          severity: high
#          object-templates:
#            - complianceType: musthave
#              objectDefinition:
#                apiVersion: v1
#                kind: Namespace
#                metadata:
#                  name: stackrox
    # secured instance
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: secured-cluster-instance-create
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: SecuredCluster
                metadata:
                  name: stackrox-secured-cluster-services
                  namespace: stackrox
                spec:
                  clusterName: '{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}'
                  ### Patch for ROX-23463
                  ### https://access.redhat.com/solutions/7062920
                  overlays:
                  - apiVersion: apps/v1
                    kind: DaemonSet
                    name: collector
                    patches:
                    - path: spec.template.spec.containers[name:collector].env[-1]
                      value: |
                        name: ROX_COLLECTOR_SINSP_CPU_PER_BUFFER
                        value: "4"
                    - path: spec.template.spec.containers[name:collector].env[-1]
                      value: |
                        name: ROX_COLLECTOR_SINSP_THREAD_CACHE_SIZE
                        value: "8192"
                    - path: spec.template.spec.containers[name:collector].env[-1]
                      value: |
                        name: ROX_COLLECTOR_SINSP_BUFFER_SIZE
                        value: "1048576"
                  ### End patch for ROX-23463
                  monitoring:
                    openshift:
                      enabled: true
                  auditLogs:
                    collection: Auto
                  admissionControl:
                    listenOnUpdates: true
                    bypass: BreakGlassAnnotation
                    contactImageScanners: DoNotScanInline
                    listenOnCreates: true
                    replicas: 3
                    timeoutSeconds: 20
                    listenOnEvents: true
                  scannerV4:
                    db:
                      persistence:
                        persistentVolumeClaim:
                          claimName: scanner-v4-db
                    indexer:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 5
                        minReplicas: 2
                        replicas: 3
                    scannerComponent: Default
                  scanner:
                    analyzer:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 5
                        minReplicas: 2
                        replicas: 3
                    scannerComponent: AutoSense
                  perNode:
                    collector:
                      collection: CORE_BPF
                      forceCollection: false
                      imageFlavor: Regular
                    taintToleration: TolerateTaints
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: secured-cluster-instance-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: SecuredCluster
                metadata:
                  name: stackrox-secured-cluster-services
                  namespace: stackrox
                status:
                  conditions:
                  - type: Deployed
                    status: "True"
...


