apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
### TEST1-PREPRDO1 DEPLOYMENT ###
  - test1-preprod1/resources.yaml
  - test1-preprod1/test1-preprod1.yaml

### TEST2-PREPROD1 DEPLOYMENT ###
  #- test2-preprod1/resources.yaml
  #- test2-preprod1/test2-preprod1.yaml