# The backup job is executed every 8 hours: schedule: "5 */8 * * *".
#
# If the schedule is modified, the "find" command in the script must also be updated to delete the old files.
# To keep the last two backups, any file older than 2 times the schedule period is deleted, for 8 hours, it is 8x60x2=960: find /home/core/assets/backup -type f -mmin +"961" -delete'
#
# The completed or finished jobs are deleted after 25200 seconds (7 hour) with ttlSecondsAfterFinished: 3600 - This is done to get the policy out of non compliant state if a backup job failed for some temporary reason, in that case the failed job stays around forever unless it is deleted manually or with ttlSecondsAfterFinished.
#
# The backup job also pushes the last backup to an sftp server.
#
# This policy depends on an ssh key required to connect to the sftp server that must be installed in the master node.  The dependency is not explicitly defined in this policy because the ssh key is copied by a machine config.
#
#The configuration policy that checks for the successful execution of the backup jobs (etcd-backup-job-check), looks for any failed job, if one exists the whole policy is non compliant.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/description: Creates the cronjob that backups etcd database
  name: etcd-backup
  namespace: policies-mano
spec:
  disabled: false
  policy-templates:
#Create Namespace for etcd backup
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: etcd-backup-namespace
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: ocp-etcd-backup
#Create Service Account
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: etcd-backup-namespace
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: etcd-backup-service-account
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            kind: ServiceAccount
            apiVersion: v1
            metadata:
              name: openshift-backup
              namespace: ocp-etcd-backup
              labels:
                app: openshift-backup
#Create Cluster Role
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: etcd-backup-cluster-role
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: cluster-etcd-backup
            rules:
            - apiGroups: [""]
              resources:
                 - "nodes"
              verbs: ["get", "list"]
            - apiGroups: [""]
              resources:
                 - "pods"
                 - "pods/log"
                 - "pods/attach"
              verbs: ["get", "list", "create", "delete", "watch"]
            - apiGroups: [""]
              resources:
                 - "namespaces"
              verbs: ["get", "list", "create"]
#Create ClusterRoleBinding
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: etcd-backup-cluster-role
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: etcd-backup-cluster-role-binding
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            kind: ClusterRoleBinding
            apiVersion: rbac.authorization.k8s.io/v1
            metadata:
              name: openshift-backup
              labels:
                app: openshift-backup
            subjects:
              - kind: ServiceAccount
                name: openshift-backup
                namespace: ocp-etcd-backup
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cluster-etcd-backup
#Add service account to SCC "privileged"
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: etcd-backup-service-account
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: etcd-backup-assign-scc
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: system:openshift:scc:privileged
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: system:openshift:scc:privileged
            subjects:
            - kind: ServiceAccount
              name: openshift-backup
              namespace: ocp-etcd-backup
#Create Backup CronJob
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: etcd-backup-cluster-role
       namespace: ""
       compliance: Compliant
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: etcd-backup-namespace
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: etcd-backup-cronjob
      spec:
        pruneObjectBehavior: None
        remediationAction: enforce
        severity: high
        object-templates:
        - complianceType: mustonlyhave
          objectDefinition:
            kind: CronJob
            apiVersion: batch/v1
            metadata:
              name: openshift-backup
              namespace: ocp-etcd-backup
              labels:
                app: openshift-backup
            spec:
              schedule: "5 */8 * * *"
              concurrencyPolicy: Forbid
              successfulJobsHistoryLimit: 5
              failedJobsHistoryLimit: 5
              jobTemplate:
                metadata:
                  labels:
                    app: openshift-backup
                spec:
                  ttlSecondsAfterFinished: 36000
                  backoffLimit: 0
                  template:
                    metadata:
                      labels:
                        app: openshift-backup
                    spec:
                      containers:
                        - name: backup
                          image: "registry.redhat.io/openshift4/ose-cli"
                          command:
                            - "/bin/bash"
                            - "-c"
                            - oc get nodes -l node-role.kubernetes.io/master --no-headers -o name | head -n 1 |xargs -I {} -- oc debug {} --image=registry.redhat.io/ubi9/toolbox --to-namespace=ocp-etcd-backup -- bash -c 'chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/assets/backup && chroot /host sudo -E find /home/core/assets/backup -type f -mmin +"961" -delete && ls -1tr /host/home/core/assets/backup/|tail -n2 | xargs -I {} -- scp -i /host/home/core/.ssh/sftp_server_key -o StrictHostKeyChecking=no /host/home/core/assets/backup/{} rhocpsftp@IP_ADDRESS_11:jz-ocp-hub1-prod/{{ (lookup "config.openshift.io/v1" "DNS" "" "cluster").spec.baseDomain }}-{}'
                      restartPolicy: "Never"
                      terminationGracePeriodSeconds: 30
                      activeDeadlineSeconds: 300
                      dnsPolicy: "ClusterFirst"
                      serviceAccountName: "openshift-backup"
                      serviceAccount: "openshift-backup"
#Check for job completion
  - extraDependencies:
     - apiVersion: policy.open-cluster-management.io/v1
       kind: ConfigurationPolicy
       name: etcd-backup-cronjob
       namespace: ""
       compliance: Compliant
    objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: etcd-backup-job-check
      spec:
        pruneObjectBehavior: None
        remediationAction: inform
        severity: high
        object-templates:
        - complianceType: mustnothave
          objectDefinition:
            apiVersion: batch/v1
            kind: Job
            metadata:
              namespace: ocp-etcd-backup
              labels:
                app: openshift-backup
            status:
              conditions:
                - reason: BackoffLimitExceeded
                  status: "True"
                  type: Failed
              failed: 1
