---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-ca-cert
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  ca.crt: |
{{ .Values.mgmt.authentication.ldap.crt | b64dec | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-ca-cert
  namespace: openshift-authentication
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  ca.crt: |
{{ .Values.mgmt.authentication.ldap.crt | b64dec | indent 4 }}
