apiVersion: v1
kind: Secret
metadata:
  name: ca-cert-bundle
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: '1'
type: Opaque
stringData:
  bundle-ca.crt: |-
{{ .Values.mgmt.authentication.ldap.crt | b64dec | indent 4 }}
{{ .Values.mgmt.gitops.caCerts.certificate_b64 | b64dec | indent 4 }}